name: Build & Deploy Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install dependencies
        run: flutter pub get
        working-directory: frontend

      - name: Build web
        run: flutter build web --release
        working-directory: frontend

      - name: List build outputs
        run: ls -R build/web
        working-directory: frontend

      - name: Copy web files to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Remove old files
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "rm -rf ~/nginx-web/*"

          # Upload new web build
          scp -r -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 \
            build/web/* \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/nginx-web/

        working-directory: frontend

      - name: Verify remote web files
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "ls -lh ~/nginx-web/"
